### ISSUE TITLE
Fabri cuando puedas leeme

### ISSUE THREAD

**Issue by Taielmolina01** [Taielmolina01/EBT#23]
no me compila, es porque agregue la carpeta clases/ y deje las clases ahi pero cambie el path en el Makefile pero no me actualiza el pdf:/

dejo todo en tus manos

**Comment by lima-limon-inc** [comment]
o7

**Comment by lima-limon-inc** [comment]
@Taielmolina01  

El problema era que no estaban escapados los `%`. En latex los comentarios son con % y suelen causar problemas. 

Habia que escaparlos y listo. El script andaba bien! Si te fijabas el output de `xelatex` decia:

```
Error producing PDF.
```

Todo listo o7

**Comment by Taielmolina01** [comment]
mi padre
